### ISSUE TITLE
no playhouse module

### ISSUE THREAD

**Issue by vivianandliliqin** [boylegu/SanicCRUD-vue#51]
from playhouse.shortcuts import model_to_dict
got error no playhouse module

SanicCRUD-vue/sanic_crudvue/crud/views.py", line 4, in <module>
    from playhouse.shortcuts import model_to_dict
ModuleNotFoundError: No module named 'playhouse'

**Comment by vivianandliliqin** [comment]
哦 是 pewee里的
pip install -r requirement.txt

**Comment by zhenghaicaidd01** [comment]
是 peewee 不是 pewee
